image: Ubuntu2004

platform:
  - x64

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: v20.12.2

install:
  - nvm install $nodejs_version
  - nvm use $nodejs_version
  - yarn

build_script:
  - yarn build
  - yarn build:android

artifacts:
  - path: android\app\build\outputs\apk\debug\app-debug.apk
    name: electrostat-cfg-debug.apk

deploy:
- provider: GitHub
  description: Draft release
  auth_token:
    secure: F9LLS3TkKo/pFmBa0e7yTe4j75rcAcQqNHW7eQZQWSiREi9fl41XxSSrnjLoVR5UDhuiqVDV5U6fQ+36S9EC/uRZj7UHtFso6HGo5nqmdXZBhFUjMg0IQ4skcrRqGUgq
  draft: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

test: false
